replace_sensor:
  description: Replaces an external sensor
  # target:
  #   entity:
  #     domain: plant
  fields:
    meter_entity:
      name: Meter entity
      description: The meter entity to replace the sensor for
      example: plant.my_plant_current_temperature
      required: true
      selector:
        entity:
          domain: sensor
          integration: plant

    new_sensor:
      name: Sensor entity
      description: Entity id of the new sensor. Leave blank to remove sensor.
      example: sensor.new_temperature_outdoor
      required: false
      selector:
        entity:
          domain: sensor

remove_plant:
  description: Löscht eine Pflanze und alle zugehörigen Entities
  fields:
    plant_entity:
      name: Plant entity
      description: Die zu löschende Pflanze
      example: plant.my_plant
      required: true
      selector:
        entity:
          domain: plant
          integration: plant

create_plant:
  description: Erstellt eine neue Pflanze
  fields:
    name:
      name: Name
      description: Name der Pflanze
      example: "Meine Pflanze"
      required: true
      selector:
        text:
    plant_emoji:
      name: Icon
      default: "🥦"
      required: false
      selector:
        text:
    strain:
      name: Strain
      description: Sortenname für OpenPlantbook Suche
      example: "White Widow"
      required: true
      selector:
        text:
    breeder:
      name: Breeder
      description: Züchter/Hersteller
      example: "Green House Seeds"
      required: true
      selector:
        text:
    growth_phase:
      name: Growth Phase
      description: Aktuelle Wachstumsphase
      required: true
      default: "Wurzeln"
      selector:
        select:
          options:
            - "Samen"
            - "Keimen"
            - "Wurzeln" 
            - "Wachstum"
            - "Blüte"
            - "Entfernt"
            - "Geerntet"
    temperature_sensor:
      name: Temperature Sensor
      description: Temperatursensor
      required: false
      selector:
        entity:
          domain: sensor
          device_class: temperature
    moisture_sensor:
      name: Moisture Sensor  
      description: Feuchtigkeitssensor
      required: false
      selector:
        entity:
          domain: sensor
          device_class: moisture
    conductivity_sensor:
      name: Conductivity Sensor
      description: Leitfähigkeitssensor
      required: false
      selector:
        entity:
          domain: sensor
    illuminance_sensor:
      name: Illuminance Sensor
      description: Helligkeitssensor
      required: false
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    humidity_sensor:
      name: Humidity Sensor
      description: Luftfeuchtigkeitssensor
      required: false
      selector:
        entity:
          domain: sensor
          device_class: humidity
    power_consumption_sensor:
      name: Power Consumption Sensor
      description: Energieverbrauchssensor
      required: false
      selector:
        entity:
          domain: sensor
          device_class: energy
    ph_sensor:
      name: pH Sensor
      description: pH-Wert Sensor
      required: false
      selector:
        entity:
          domain: sensor
          device_class: ph

move_to_cycle:
  name: Move to cycle
  description: Moves one or more plants to a cycle device. If no cycle is specified, removes plants from their current cycle.
  fields:
    plant_entity:
      name: Plant entities
      description: The plants to move or remove from cycle
      example: "plant.my_plant"
      required: true
      selector:
        entity:
          domain: plant
          multiple: true
    cycle_entity:
      name: Cycle entity
      description: The cycle device to move the plants to. Leave empty to remove from current cycle.
      example: "cycle.my_cycle"
      required: false
      selector:
        entity:
          domain: cycle

create_cycle:
  name: Create cycle
  description: Creates a new cycle entity.
  fields:
    name:
      name: Name
      description: Name of the cycle
      required: true
      selector:
        text:
    plant_emoji:
      name: Emoji
      description: Emoji to display next to the cycle name
      default: "🔄"
      selector:
        text:

remove_cycle:
  name: Remove cycle
  description: Removes a cycle entity and all its associated entities
  fields:
    cycle_entity:
      name: Cycle entity
      description: The cycle to remove
      example: "cycle.my_cycle"
      required: true
      selector:
        entity:
          domain: cycle

clone_plant:
  name: Clone Plant
  description: Create a clone/cutting of an existing plant device.
  fields:
    source_entity_id:
      name: Source Plant
      description: The plant device to clone
      required: true
      selector:
        entity:
          domain: plant
    name:
      name: Name
      description: Name for the new plant clone. If not provided, will use source plant name with incrementing number
      required: false
      example: "Clone of My Plant"
      selector:
        text:
    temperature_sensor:
      name: Temperature Sensor
      description: Temperature sensor for the clone
      required: false
      selector:
        entity:
          domain: sensor
          device_class: temperature
    moisture_sensor:
      name: Moisture Sensor
      description: Moisture sensor for the clone
      required: false
      selector:
        entity:
          domain: sensor
          device_class: moisture
    conductivity_sensor:
      name: Conductivity Sensor
      description: Conductivity sensor for the clone
      required: false
      selector:
        entity:
          domain: sensor
    illuminance_sensor:
      name: Illuminance Sensor
      description: Illuminance sensor for the clone
      required: false
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    humidity_sensor:
      name: Humidity Sensor
      description: Humidity sensor for the clone
      required: false
      selector:
        entity:
          domain: sensor
          device_class: humidity
    power_consumption_sensor:
      name: Power Consumption Sensor
      description: Power consumption sensor for the clone
      required: false
      selector:
        entity:
          domain: sensor
          device_class: energy
    ph_sensor:
      name: pH Sensor
      description: pH-Wert Sensor für den Klon
      required: false
      selector:
        entity:
          domain: sensor
          device_class: ph

update_plant_attributes:
  name: Update plant attributes
  description: Update the attributes of a plant
  fields:
    entity_id:
      name: Plant entity
      description: The plant entity to update
      required: true
      selector:
        entity:
          domain: plant
          integration: plant
    strain:
      name: Strain
      description: Plant strain name
      example: "White Widow"
      selector:
        text:
          type: text
    breeder:
      name: Breeder
      description: Plant breeder/manufacturer
      example: "Green House Seeds"
      selector:
        text:
          type: text
    original_flowering_duration:
      name: Original Flowering Duration
      description: Original duration of flowering phase in days (from OpenPlantbook or initial setup)
      example: 63
      selector:
        number:
          min: 1
          max: 365
          mode: box
    pid:
      name: Plant ID
      description: Unique plant identifier
      example: "WW_GHS"
      selector:
        text:
          type: text
    sorte:
      name: Type/Sort
      description: Plant type or sort
      example: "Hybrid"
      selector:
        text:
          type: text
    feminized:
      name: Feminized
      description: Feminization status
      example: "Yes"
      selector:
        text:
          type: text
    timestamp:
      name: Timestamp
      description: Last update timestamp
      example: "2024-03-19"
      selector:
        text:
          type: text
    effects:
      name: Effects
      description: Plant effects
      example: "Relaxing, Creative"
      selector:
        text:
          type: text
    smell:
      name: Smell
      description: Smell characteristics
      example: "Citrus, pine"
      selector:
        text:
          type: text
    taste:
      name: Taste
      description: Taste characteristics
      example: "Sweet, earthy"
      selector:
        text:
          type: text
    phenotype:
      name: Phenotype
      description: Plant phenotype
      example: "Indica dominant"
      selector:
        text:
          type: text
    hunger:
      name: Hunger
      description: Plant nutrient requirements
      example: "Medium"
      selector:
        text:
          type: text
    growth_stretch:
      name: Growth stretch
      description: Plant growth stretch characteristics
      example: "2x"
      selector:
        text:
          type: text
    flower_stretch:
      name: Flower stretch  
      description: Plant flower stretch characteristics
      example: "1.5x"
      selector:
        text:
          type: text
    mold_resistance:
      name: Mold resistance
      description: Plant mold resistance level
      example: "High"
      selector:
        text:
          type: text
    difficulty:
      name: Difficulty
      description: Growing difficulty level
      example: "Medium"
      selector:
        text:
          type: text
    yield:
      name: Yield
      description: Expected yield information
      example: "500-600g/m²"
      selector:
        text:
          type: text
    notes:
      name: Notes
      description: Additional notes about the plant
      example: "Responds well to LST"
      selector:
        text:
          multiline: true
    website:
      name: Website
      description: Related website URL
      example: "https://example.com/strain-info"
      selector:
        text:
          type: text
    infotext1:
      name: Info Text 1
      description: Additional information text 1
      example: "Growing tips"
      selector:
        text:
          multiline: true
    infotext2:
      name: Info Text 2
      description: Additional information text 2
      example: "History"
      selector:
        text:
          multiline: true
    lineage:
      name: Lineage
      description: Plant genetic lineage/ancestry
      example: "Skunk #1 x White Widow"
      selector:
        text:
          type: text
    images:
      name: Images
      description: Liste von Bildpfaden oder URLs (durch Komma getrennt)
      example: "/local/images/plant1.jpg, /local/images/plant2.jpg"
      selector:
        text:
          multiline: true
    samen_beginn:
      name: Samen Beginn
      description: Startdatum der Samen-Phase
      example: "2024-01-01"
      selector:
        text:
          type: text
    samen_dauer:
      name: Samen Dauer
      description: Dauer der Samen-Phase in Tagen
      example: "7"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    keimen_beginn:
      name: Keimen Beginn
      description: Startdatum der Keimungs-Phase
      example: "2024-01-08"
      selector:
        text:
          type: text
    keimen_dauer:
      name: Keimen Dauer
      description: Dauer der Keimungs-Phase in Tagen
      example: "7"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    wurzeln_beginn:
      name: Wurzeln Beginn
      description: Startdatum der Wurzel-Phase
      example: "2024-01-15"
      selector:
        text:
          type: text
    wurzeln_dauer:
      name: Wurzeln Dauer
      description: Dauer der Wurzel-Phase in Tagen
      example: "14"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    wachstum_beginn:
      name: Wachstum Beginn
      description: Startdatum der Wachstums-Phase
      example: "2024-01-29"
      selector:
        text:
          type: text
    wachstum_dauer:
      name: Wachstum Dauer
      description: Dauer der Wachstums-Phase in Tagen
      example: "30"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    blüte_beginn:
      name: Blüte Beginn
      description: Startdatum der Blüte-Phase
      example: "2024-02-28"
      selector:
        text:
          type: text
    blüte_dauer:
      name: Blüte Dauer
      description: Dauer der Blüte-Phase in Tagen
      example: "63"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    geerntet:
      name: Geerntet
      description: Datum der Ernte
      example: "2024-05-01"
      selector:
        text:
          type: text
    geerntet_dauer:
      name: Geerntet Dauer
      description: Dauer seit der Ernte in Tagen
      example: "0"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    entfernt:
      name: Entfernt
      description: Datum der Entfernung
      example: "2024-05-01"
      selector:
        text:
          type: text
    entfernt_dauer:
      name: Entfernt Dauer
      description: Dauer seit der Entfernung in Tagen
      example: "0"
      selector:
        number:
          min: 0
          max: 365
          mode: box
    position_x:
      name: X-Position
      description: X-Koordinate der Pflanze (wird in der Growth Phase gespeichert)
      example: 10.5
      selector:
        number:
          min: -1000
          max: 1000
          step: 0.1
          mode: box
    position_y:
      name: Y-Position
      description: Y-Koordinate der Pflanze (wird in der Growth Phase gespeichert)
      example: 20.5
      selector:
        number:
          min: -1000
          max: 1000
          step: 0.1
          mode: box

move_to_area:
  name: Move to area
  description: Moves one or more plants to an area. If no area is specified, removes plants from their current area.
  fields:
    device_id:
      name: Device ID
      description: The ID of the device(s) to add to the area.
      required: true
      selector:
        device:
          multiple: true
    area_id:
      name: Area
      description: The area to move the plants to. Leave empty to remove from current area.
      example: "living_room"
      required: false
      selector:
        area:

add_image:
  name: Add Image
  description: Fügt ein Bild zu einer Pflanze oder einem Cycle hinzu. Das Bild wird im konfigurierten Pfad gespeichert.
  fields:
    entity_id:
      name: Entity
      description: Die Pflanze oder der Cycle, zu dem das Bild hinzugefügt werden soll
      required: true
      selector:
        entity:
          domain:
            - plant
            - cycle
    image_url:
      name: Image URL
      description: Die URL des Bildes, das heruntergeladen werden soll
      example: "https://example.com/plant-image.jpg"
      required: true
      selector:
        text:
          type: url

change_position:
  name: Change Position
  description: Ändert die Position einer Pflanze mit x- und y-Koordinaten. Die Position wird in der Growth Phase gespeichert und eine Historie geführt.
  fields:
    entity_id:
      name: Plant entity
      description: Die Pflanze, deren Position geändert werden soll
      required: true
      selector:
        entity:
          domain: plant
          integration: plant
    position_x:
      name: X-Position
      description: X-Koordinate der Pflanze
      example: 10.5
      selector:
        number:
          min: -1000
          max: 1000
          step: 0.1
          mode: box
    position_y:
      name: Y-Position
      description: Y-Koordinate der Pflanze
      example: 20.5
      selector:
        number:
          min: -1000
          max: 1000
          step: 0.1
          mode: box

add_custom_treatment:
  name: Add Custom Treatment
  description: Add a custom treatment option to a plant's treatment selector.
  fields:
    entity_id:
      name: Plant Entity
      description: The plant entity to add the custom treatment to
      required: true
      selector:
        entity:
          domain: plant
          integration: plant
    treatment_name:
      name: Treatment Name
      description: Name of the custom treatment to add
      example: "my custom treatment"
      required: true
      selector:
        text:

remove_custom_treatment:
  name: Remove Custom Treatment
  description: Remove a custom treatment option from a plant's treatment selector.
  fields:
    entity_id:
      name: Plant Entity
      description: The plant entity to remove the custom treatment from
      required: true
      selector:
        entity:
          domain: plant
          integration: plant
    treatment_name:
      name: Treatment Name
      description: Name of the custom treatment to remove
      example: "my custom treatment"
      required: true
      selector:
        text: