name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 15 * *'

jobs:

  black:
    name: Python Code Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Black
        run: pip install black
      - name: Black Code Format Check
        run: black . --check --fast --diff

  validate:
    name: Check hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@main"
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
